### PR TITLE
Usage and documentation fixes, part 1

### LINKED ISSUE #6: Config file values should be bound to and overridable by command line flags
You can specify your "context" in the config file (default `~/.containership/csctl.yaml`).       
Examples are `organization` and `cluster`. However, these values are not picked up properly right now and instead, flags must always be passed.

It should be the case that these values are bound to each other such that the config file values are used by default, but they are overridable by the command line flags. For example, if I specify

```
organization: abc
```

in my config file and do not provide the `--organization` flag, then the organization `abc` should be used for requests. However, if I specify `--organization xyz` on the command line, then `xyz` should be used.

### LINKED ISSUE #66: Update usage messages to be useful across the entire tool
#### What is the current behavior?

This tool has been useful for some people internally that know how to use it already. It can't be useful to other people in its current form, because the usage messages (where they even exist) are not useful.

#### What is the expected behavior?

As part of this, we should devise a way to have one source of truth for valid parameters (and defaults), and avoid hardcoding them in places. We should dynamically pull the valid values into the usage messages if possible so we're not repeating ourselves.

- Update the usage messages across the board to make sense
- Usage messages must include valid values for things (e.g. plugin types, implementations, etc - ideally not hardcoded)
- The main usage message `csctl -h` should be quite detailed, as well as command usage messages `csctl get -h`, `csctl get cluster -h`, etc.

### PR DESCRIPTION
**Pull request by mattkelly**
#### What does this pull request accomplish?

 Fix some usage stuff and expand on docs. See individual commits.

 #### What issue(s) does this fix?
* Fixes #6
* Closes #66

 #### Additional Considerations

 ### Testing

 Verified that flags on command line properly override config file values.

 ### Dependencies
 None

### CODE REVIEW

**Comment by mattkelly** [comment]
Tests are fixed. I had removed some errors that didn't make sense to remove.

**Comment by mattkelly** [comment]
I'm just going to keep tacking better usage onto this PR instead of opening new ones. Please hold.

**Comment by mattkelly** [comment]
Added a bunch more usage info. Going to call this good enough for now, pending review. We need to figure out the best way to document the template stuff, which is obviously a bit more involved :)

File: cmd/create_cluster.go [hunk 1]
```diff
@@ -15,27 +15,65 @@ var createClusterOpts options.ClusterCreate
...
+
+To list available providers, use:
+
+	csctl get providers
+
+Plugins are specified using flags corresponding to the plugin type. For
+example, to specify the autoscaler plugin, use --plugin-autoscaler. The
+implementation and version are provided as follows, for example:
+
+	csctl create cluster --plugin-autoscaler=cerebral@0.3.2-alpha
```
Comment (ashleyschuett) [inline cmd/create_cluster.go]: I think this example is a little misleading, it makes it look like you can create a cluster with little of information. Maybe something like `csctl create cluster ... --plugin-autoscaler=cerebral@0.3.2-alpha` or `csctl create cluster digitalocean ... --plugin-autoscaler=cerebral@0.3.2-alpha`

I don't love either of those options though

File: resource/options/cluster_create.go [hunk 2]
```diff
@@ -35,19 +35,19 @@ type ClusterCreate struct {
 // DefaultAndValidate defaults and validates all options
 func (o *ClusterCreate) DefaultAndValidate() error {
 	if o.TemplateID == "" {
-		return errors.New("please specify template with --template")
+		return errors.New("template ID is required")
```
Comment (ashleyschuett) [inline resource/options/cluster_create.go]: I rather like having the flag name in the error message, then the user doesn't need to look in the help and find what the error corresponds to. But that's just personal preference.

Comment (ashleyschuett) [reply resource/options/cluster_create.go]: no strong feeling either way, up to you.

File: cmd/create_cluster.go (hunk 1 above)
Comment (mattkelly) [reply cmd/create_cluster.go]: Oh yeah, totally forgot about the whole cloud provider subcommand thing...will fix 😬

File: resource/options/cluster_create.go (hunk 2 above)
Comment (mattkelly) [reply resource/options/cluster_create.go]: This change is because the flag is now required by cobra. Technically this can never happen during normal usage. However, at this layer it still made sense to keep the errors to me in case we decide to reuse this function somewhere for some reason.

**Comment by mattkelly** [comment]
Updated @ashleyschuett
